spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/configdb

  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/configdb
    password: root

  application:
    name: config-server

  cloud:
    config:
      server:
        mongodb:
          order: 0
          enabled: true
          collection: properties
        jdbc:
          sql: SELECT key, value FROM properties WHERE application=? AND profile=? AND label=?
          enabled: true
          order: 1
        vault:
          authentication: token
          token: root
          order: 2
          host: 127.0.0.1
          port: 8200
          scheme: http
          #default-key: spring-boot-datasource-config
          #default-label: main
          kv-version: 2
          profile-separator: /

  profiles:
    active: mongodb # jdbc, vault or mongodb
server:
  port: 8888

