spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    url: jdbc:postgresql://localhost:5432/configdb
    password: root
  application:
    name: config-server
  cloud:
    config:
      server:
#        jdbc:
#          sql: SELECT key, value FROM properties WHERE application=? AND profile=? AND label=?
#          enabled: true
#          order: 1
        vault:
          authentication: token
          token: root
          order: 1
          host: 127.0.0.1
          port: 8200
          scheme: http
          #default-key: spring-boot-datasource-config
          #default-label: main
          kv-version: 2
          profile-separator: /

  profiles:
    active: vault
server:
  port: 8888

